New-ADOrganizationalUnit -Name "Direction" -Path "DC=evil,DC=labo"
New-ADOrganizationalUnit -Name "Pedagogie" -Path "DC=evil,DC=labo"
New-ADOrganizationalUnit -Name "Administratif" -Path "DC=evil,DC=labo"
New-ADOrganizationalUnit -Name "Intervenants" -Path "DC=evil,DC=labo"
New-ADOrganizationalUnit -Name "Auditeurs 1" -Path "DC=evil,DC=labo"
New-ADOrganizationalUnit -Name "Auditeurs 2" -Path "DC=evil,DC=labo"

New-ADUser -Name "Rick" -GivenName "Rick" -Surname "Sanchez" -SamAccountName "Rick" -UserPrincipalName "Rick" -Path "OU=Direction,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Morty" -GivenName "Morty" -Surname "Smith" -SamAccountName "Morty" -UserPrincipalName "Morty" -Path "OU=Direction,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Summer" -GivenName "Summer" -Surname "Smith" -SamAccountName "Summer" -UserPrincipalName "Summer" -Path "OU=Direction,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true

New-ADUser -Name "Franck" -GivenName "Franck" -Surname "Nicolas" -SamAccountName "Franck" -UserPrincipalName "Franck" -Path "OU=Pedagogie,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Nicolas" -GivenName "Nicolas" -Surname "Nicolas" -SamAccountName "Nicolas" -UserPrincipalName "Nicolas" -Path "OU=Pedagogie,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Jean" -GivenName "Jean" -Surname "Jean" -SamAccountName "Jean" -UserPrincipalName "Jean" -Path "OU=Pedagogie,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true

New-ADUser -Name "Romain" -GivenName "Romain" -Surname "Hugues" -SamAccountName "Romain" -UserPrincipalName "Romain" -Path "OU=Administratif,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Hugues" -GivenName "Hugues" -Surname "Hugues" -SamAccountName "Hugues" -UserPrincipalName "Hugues" -Path "OU=Administratif,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Paul" -GivenName "Paul" -Surname "Paul" -SamAccountName "Paul" -UserPrincipalName "Paul" -Path "OU=Administratif,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true

New-ADGroup -Name "Intervenants" -GroupScope Global
New-ADGroup -Name "Auditeurs 1" -GroupScope Global
New-ADGroup -Name "Auditeurs 2" -GroupScope Global

New-ADUser -Name "Intervenant1" -GivenName "Intervenant1" -Surname "Intervenant1" -SamAccountName "Intervenant1" -UserPrincipalName "Intervenant1" -Path "OU=Intervenants,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Intervenant2" -GivenName "Intervenant2" -Surname "Intervenant2" -SamAccountName "Intervenant2" -UserPrincipalName "Intervenant2" -Path "OU=Intervenants,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Intervenant3" -GivenName "Intervenant3" -Surname "Intervenant3" -SamAccountName "Intervenant3" -UserPrincipalName "Intervenant3" -Path "OU=Intervenants,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Intervenant4" -GivenName "Intervenant4" -Surname "Intervenant4" -SamAccountName "Intervenant4" -UserPrincipalName "Intervenant4" -Path "OU=Intervenants,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Intervenant5" -GivenName "Intervenant5" -Surname "Intervenant5" -SamAccountName "Intervenant5" -UserPrincipalName "Intervenant5" -Path "OU=Intervenants,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Intervenant6" -GivenName "Intervenant6" -Surname "Intervenant6" -SamAccountName "Intervenant6" -UserPrincipalName "Intervenant6" -Path "OU=Intervenants,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Intervenant7" -GivenName "Intervenant7" -Surname "Intervenant7" -SamAccountName "Intervenant7" -UserPrincipalName "Intervenant7" -Path "OU=Intervenants,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Intervenant8" -GivenName "Intervenant8" -Surname "Intervenant8" -SamAccountName "Intervenant8" -UserPrincipalName "Intervenant8" -Path "OU=Intervenants,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Intervenant9" -GivenName "Intervenant9" -Surname "Intervenant9" -SamAccountName "Intervenant9" -UserPrincipalName "Intervenant9" -Path "OU=Intervenants,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Intervenant10" -GivenName "Intervenant10" -Surname "Intervenant10" -SamAccountName "Intervenant10" -UserPrincipalName "Intervenant10" -Path "OU=Intervenants,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true

New-ADUser -Name "Auditeur1" -GivenName "Auditeur1" -Surname "Auditeur1" -SamAccountName "Auditeur1" -UserPrincipalName "Auditeur1" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur2" -GivenName "Auditeur2" -Surname "Auditeur2" -SamAccountName "Auditeur2" -UserPrincipalName "Auditeur2" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur3" -GivenName "Auditeur3" -Surname "Auditeur3" -SamAccountName "Auditeur3" -UserPrincipalName "Auditeur3" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur4" -GivenName "Auditeur4" -Surname "Auditeur4" -SamAccountName "Auditeur4" -UserPrincipalName "Auditeur4" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur5" -GivenName "Auditeur5" -Surname "Auditeur5" -SamAccountName "Auditeur5" -UserPrincipalName "Auditeur5" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur6" -GivenName "Auditeur6" -Surname "Auditeur6" -SamAccountName "Auditeur6" -UserPrincipalName "Auditeur6" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur7" -GivenName "Auditeur7" -Surname "Auditeur7" -SamAccountName "Auditeur7" -UserPrincipalName "Auditeur7" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur8" -GivenName "Auditeur8" -Surname "Auditeur8" -SamAccountName "Auditeur8" -UserPrincipalName "Auditeur8" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur9" -GivenName "Auditeur9" -Surname "Auditeur9" -SamAccountName "Auditeur9" -UserPrincipalName "Auditeur9" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur10" -GivenName "Auditeur10" -Surname "Auditeur10" -SamAccountName "Auditeur10" -UserPrincipalName "Auditeur10" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur11" -GivenName "Auditeur11" -Surname "Auditeur11" -SamAccountName "Auditeur11" -UserPrincipalName "Auditeur11" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur12" -GivenName "Auditeur12" -Surname "Auditeur12" -SamAccountName "Auditeur12" -UserPrincipalName "Auditeur12" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur13" -GivenName "Auditeur13" -Surname "Auditeur13" -SamAccountName "Auditeur13" -UserPrincipalName "Auditeur13" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur14" -GivenName "Auditeur14" -Surname "Auditeur14" -SamAccountName "Auditeur14" -UserPrincipalName "Auditeur14" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur15" -GivenName "Auditeur15" -Surname "Auditeur15" -SamAccountName "Auditeur15" -UserPrincipalName "Auditeur15" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur16" -GivenName "Auditeur16" -Surname "Auditeur16" -SamAccountName "Auditeur16" -UserPrincipalName "Auditeur16" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur17" -GivenName "Auditeur17" -Surname "Auditeur17" -SamAccountName "Auditeur17" -UserPrincipalName "Auditeur17" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur18" -GivenName "Auditeur18" -Surname "Auditeur18" -SamAccountName "Auditeur18" -UserPrincipalName "Auditeur18" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur19" -GivenName "Auditeur19" -Surname "Auditeur19" -SamAccountName "Auditeur19" -UserPrincipalName "Auditeur19" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur20" -GivenName "Auditeur20" -Surname "Auditeur20" -SamAccountName "Auditeur20" -UserPrincipalName "Auditeur20" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur21" -GivenName "Auditeur21" -Surname "Auditeur21" -SamAccountName "Auditeur21" -UserPrincipalName "Auditeur21" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur22" -GivenName "Auditeur22" -Surname "Auditeur22" -SamAccountName "Auditeur22" -UserPrincipalName "Auditeur22" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur23" -GivenName "Auditeur23" -Surname "Auditeur23" -SamAccountName "Auditeur23" -UserPrincipalName "Auditeur23" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur24" -GivenName "Auditeur24" -Surname "Auditeur24" -SamAccountName "Auditeur24" -UserPrincipalName "Auditeur24" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur25" -GivenName "Auditeur25" -Surname "Auditeur25" -SamAccountName "Auditeur25" -UserPrincipalName "Auditeur25" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur26" -GivenName "Auditeur26" -Surname "Auditeur26" -SamAccountName "Auditeur26" -UserPrincipalName "Auditeur26" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur27" -GivenName "Auditeur27" -Surname "Auditeur27" -SamAccountName "Auditeur27" -UserPrincipalName "Auditeur27" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur28" -GivenName "Auditeur28" -Surname "Auditeur28" -SamAccountName "Auditeur28" -UserPrincipalName "Auditeur28" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur29" -GivenName "Auditeur29" -Surname "Auditeur29" -SamAccountName "Auditeur29" -UserPrincipalName "Auditeur29" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur30" -GivenName "Auditeur30" -Surname "Auditeur30" -SamAccountName "Auditeur30" -UserPrincipalName "Auditeur30" -Path "OU=Auditeurs 1,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true

New-ADUser -Name "Auditeur31" -GivenName "Auditeur31" -Surname "Auditeur31" -SamAccountName "Auditeur31" -UserPrincipalName "Auditeur31" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur32" -GivenName "Auditeur32" -Surname "Auditeur32" -SamAccountName "Auditeur32" -UserPrincipalName "Auditeur32" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur33" -GivenName "Auditeur33" -Surname "Auditeur33" -SamAccountName "Auditeur33" -UserPrincipalName "Auditeur33" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur34" -GivenName "Auditeur34" -Surname "Auditeur34" -SamAccountName "Auditeur34" -UserPrincipalName "Auditeur34" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur35" -GivenName "Auditeur35" -Surname "Auditeur35" -SamAccountName "Auditeur35" -UserPrincipalName "Auditeur35" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur36" -GivenName "Auditeur36" -Surname "Auditeur36" -SamAccountName "Auditeur36" -UserPrincipalName "Auditeur36" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur37" -GivenName "Auditeur37" -Surname "Auditeur37" -SamAccountName "Auditeur37" -UserPrincipalName "Auditeur37" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur38" -GivenName "Auditeur38" -Surname "Auditeur38" -SamAccountName "Auditeur38" -UserPrincipalName "Auditeur38" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur39" -GivenName "Auditeur39" -Surname "Auditeur39" -SamAccountName "Auditeur39" -UserPrincipalName "Auditeur39" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur40" -GivenName "Auditeur40" -Surname "Auditeur40" -SamAccountName "Auditeur40" -UserPrincipalName "Auditeur40" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur41" -GivenName "Auditeur41" -Surname "Auditeur41" -SamAccountName "Auditeur41" -UserPrincipalName "Auditeur41" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur42" -GivenName "Auditeur42" -Surname "Auditeur42" -SamAccountName "Auditeur42" -UserPrincipalName "Auditeur42" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur43" -GivenName "Auditeur43" -Surname "Auditeur43" -SamAccountName "Auditeur43" -UserPrincipalName "Auditeur43" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur44" -GivenName "Auditeur44" -Surname "Auditeur44" -SamAccountName "Auditeur44" -UserPrincipalName "Auditeur44" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur45" -GivenName "Auditeur45" -Surname "Auditeur45" -SamAccountName "Auditeur45" -UserPrincipalName "Auditeur45" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur46" -GivenName "Auditeur46" -Surname "Auditeur46" -SamAccountName "Auditeur46" -UserPrincipalName "Auditeur46" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur47" -GivenName "Auditeur47" -Surname "Auditeur47" -SamAccountName "Auditeur47" -UserPrincipalName "Auditeur47" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur48" -GivenName "Auditeur48" -Surname "Auditeur48" -SamAccountName "Auditeur48" -UserPrincipalName "Auditeur48" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur49" -GivenName "Auditeur49" -Surname "Auditeur49" -SamAccountName "Auditeur49" -UserPrincipalName "Auditeur49" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur50" -GivenName "Auditeur50" -Surname "Auditeur50" -SamAccountName "Auditeur50" -UserPrincipalName "Auditeur50" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur51" -GivenName "Auditeur51" -Surname "Auditeur51" -SamAccountName "Auditeur51" -UserPrincipalName "Auditeur51" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur52" -GivenName "Auditeur52" -Surname "Auditeur52" -SamAccountName "Auditeur52" -UserPrincipalName "Auditeur52" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur53" -GivenName "Auditeur53" -Surname "Auditeur53" -SamAccountName "Auditeur53" -UserPrincipalName "Auditeur53" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur54" -GivenName "Auditeur54" -Surname "Auditeur54" -SamAccountName "Auditeur54" -UserPrincipalName "Auditeur54" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur55" -GivenName "Auditeur55" -Surname "Auditeur55" -SamAccountName "Auditeur55" -UserPrincipalName "Auditeur55" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur56" -GivenName "Auditeur56" -Surname "Auditeur56" -SamAccountName "Auditeur56" -UserPrincipalName "Auditeur56" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur57" -GivenName "Auditeur57" -Surname "Auditeur57" -SamAccountName "Auditeur57" -UserPrincipalName "Auditeur57" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur58" -GivenName "Auditeur58" -Surname "Auditeur58" -SamAccountName "Auditeur58" -UserPrincipalName "Auditeur58" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur59" -GivenName "Auditeur59" -Surname "Auditeur59" -SamAccountName "Auditeur59" -UserPrincipalName "Auditeur59" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true
New-ADUser -Name "Auditeur60" -GivenName "Auditeur60" -Surname "Auditeur60" -SamAccountName "Auditeur60" -UserPrincipalName "Auditeur60" -Path "OU=Auditeurs 2,DC=evil,DC=labo" -AccountPassword (ConvertTo-SecureString -AsPlainText "Password@123" -Force) -Enabled $true

Add-ADGroupMember -Identity "Intervenants" -Members "Intervenant1","Intervenant2","Intervenant3","Intervenant4","Intervenant5","Intervenant6","Intervenant7","Intervenant8","Intervenant9","Intervenant10"
Add-ADGroupMember -Identity "Auditeurs 1" -Members "Auditeur1","Auditeur2","Auditeur3","Auditeur4","Auditeur5","Auditeur6","Auditeur7","Auditeur8","Auditeur9","Auditeur10","Auditeur11","Auditeur12","Auditeur13","Auditeur14","Auditeur15","Auditeur16","Auditeur17","Auditeur18","Auditeur19","Auditeur20","Auditeur21","Auditeur22","Auditeur23","Auditeur24","Auditeur25","Auditeur26","Auditeur27","Auditeur28","Auditeur29","Auditeur30"
Add-ADGroupMember -Identity "Auditeurs 2" -Members "Auditeur31","Auditeur32","Auditeur33","Auditeur34","Auditeur35","Auditeur36","Auditeur37","Auditeur38","Auditeur39","Auditeur40","Auditeur41","Auditeur42","Auditeur43","Auditeur44","Auditeur45","Auditeur46","Auditeur47","Auditeur48","Auditeur49","Auditeur50","Auditeur51","Auditeur52","Auditeur53","Auditeur54","Auditeur55","Auditeur56","Auditeur57","Auditeur58","Auditeur59","Auditeur60"

Add-DnsServerPrimaryZone -Name "evil.labo" -ZoneFile "evil.labo.dns" -DynamicUpdate "Secure" -Reverse $true -MasterServers "srv-1.evil.labo" -ReplicationScope "Forest" -AllowUpdate $true -AllowTransfer $true -AllowQuery $true -AllowRecursion $true -AllowZoneTransfer $true -Confirm:$false

Add-DhcpServerv4Scope -Name "evil.labo" -StartRange "192.168.100.10" -EndRange "192.168.100.180" -SubnetMask "255.255.255.0" -LeaseDuration "1.00:00:00" -ScopeId "1" -Confirm:$false
Set-DhcpServerv4OptionDefinition -OptionId 3 -DefaultValue 192.168.100.254

Add-DnsServerResourceRecordA -Name "srv-1" -ZoneName "evil.labo" -IPv4Address "192.168.100.251"
Add-DnsServerResourceRecordA -Name "srv-2" -ZoneName "evil.labo" -IPv4Address "192.168.100.252"
Add-DnsServerResourceRecordA -Name "srv-3" -ZoneName "evil.labo" -IPv4Address "192.168.100.254"
